[workspace]
members = ["day1", "day2", "day3"]
default-members = ["day1", "day2", "day3"]

[workspace.package]
edition = "2021"

[package]
version = "0.1.0"
name = "aoc2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
