[workspace]
members = ["utils", "day1", "day2"]
default-members = ["utils", "day1", "day2"]

[workspace.package]
edition = "2021"

[package]
version = "0.1.0"
name = "aoc2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
